name: peatill
description: "an app for scheduling eating pill."
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
#  flutter_hooks: ^0.20.5
  hooks_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  gap: ^3.0.1
  image: ^4.1.6
#  intl: ^0.19.0
  logger: ^2.2.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  go_router: ^13.2.0
#  styled_widget: ^0.4.1
  flutter_svg: ^2.0.10+1
#  drift: ^2.17.0
#  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.3
  path: ^1.9.0
  sqlite3: ^2.4.2
  figma_squircle: ^0.5.3
  collection: ^1.18.0
#  dotted_border: ^2.1.0
  equatable: ^2.0.5
#  freezed: ^3.0.0-0.0.dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_gen_runner: ^5.4.0
  drift_dev: ^2.17.0
  very_good_analysis: ^5.1.0
  riverpod_generator: ^3.0.0-dev.3
  build_runner: ^2.4.9
  custom_lint: ^0.5.11
  riverpod_lint: ^3.0.0-dev.4
  go_router_builder: ^2.4.1

dependency_overrides:
  intl: 0.19.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/